jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run unit
  build:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
  deploy:
    machine:
       enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - f7:ba:96:7b:27:de:72:71:cc:9f:f1:c0:f6:7b:f7:90
      - run:
          name: Deploy Over SSH
          command: |
            scp -r dist/* $SSH_USER@$SSH_HOST:apps/devquotes-api
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
  build:
    jobs:
      - build
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch