jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run unit
  build:
    executor:
      name: node/default
      tag: '13.14'
    working_directory: ~/devquotes-api
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
      - persist_to_workspace:
          root: /home/circleci/devquotes-api
          paths: 
              - dist
  deploy:
    machine:
       enabled: true
    steps:
      - attach_workspace:
          at: /tmp/dist
      - add_ssh_keys:
          fingerprints:
            - d0:5d:03:5d:99:70:f4:7c:c5:a6:00:6c:11:1e:a0:89
      - run:
          name: Deploy Over SSH
          command: |
            echo $SSH_USER@$SSH_HOST
            scp -r /tmp/dist/* $SSH_USER@$SSH_HOST:apps/devquotes-api
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch